#!/bin/bash


# Developed for Linux
# License: GNU GPL v.3		http://www.gnu.org/licenses/gpl-3.0.en.html
# Version 7
# Destiny: Network connection statistics 
# Script usage: bash script --help


##	LINKS:
##	https://askubuntu.com/questions/993253/is-networkmanager-sending-http-requests-to-googleusercontent-com
##	http://karunsubramanian.com/network/what-is-syn_sent-socket-status/


# Check root running
[[ $EUID -ne 0 ]] && echo -e "'\e[0;31m' This script must be run as root. '\e[0m'" && exit 1


#  netmonit dependecies
source lib/lib.netmonit.dep
source lib/lib.colors
source lib/lib.pstree
source lib/lib.comm
source lib/lib.netmonit.help
source lib/lib.short


#======================================================{
LEVEL11() {
while (($#)) ; do
	#echo "loop = $# "
	case "$1" in
	--shorten) V_SHORTEN=1 ;
	;;
	--loop-sleep) V_LOOP_S=2  ;;
	# In loop, it only displays when there are new connections 
	--loop-sleep-only-new) V_LOOP_S=2 ;  V_SHORTEN=1 ; V_NEW=1 ;;
	--catch)  V_CATCH=3  ; shift ; 

	#---------------------------{
		[[ -z "$1" ]] && { echo "Error: First  argument $1  of --catch is empty" ; exit 1 ;}
		[[ -z "$2" ]] && { echo "Error: Second argument $2  of --catch is empty" ; exit 1 ;}

		case "$1" in
			pid)  CATCH=pid  ; NAME="$2" ;;
			name) CATCH=name ; NAME="$2" ;;
			*) 	echo "Error: With argument --catch . Wrong next argument: $1 " 
				echo "Available arguments: "
				echo "	pid" 
				echo "	name" 
				echo "	first-pid" 
				echo "	first-name" 
				exit ;;
		esac
		shift
	#---------------------------}
		shift
	;;
	##	Working only with loop
	--catch-all-new) CATCH=all-new ; NAME="$2" ;;
	--ps-tree) TREE=1 ;;
	--my-tree) TREE=2 ;;
	--log-all)   V_LOG=4 ;;
	#--log-only-new)   V_LOG=5 ;;
	*) echo "Error: Wrong argument: $1 "  ; exit ;;
	esac
	shift
done

#[[ $V_SHORTEN == 1 ]] && { [[ -z "$WAY" ]] && { echo "Error:  variable WAY is empty" ; exit 1 ;} ;}


echo "--loop = $V_SLEEP ; --shorten = $V_SHORTEN;  ; V_CATCH= $V_CATCH -> $CATCH $NAME ; V_LOG = $V_LOG ; --tree = $TREE"
echo =====================================


##	More in lib/lib.short
if [[ "$V_LOOP_S" == 2 ]] ; then
	while true ; do
		if [[ "$V_SHORTEN" == 1 ]] ; then
			if [[ "$V_NEW" == 1 ]] ; then
				F.SHORT.COUNT
			else
				F.SHORT
			fi
		else
			${COMM}
		fi
		sleep 1
	done
else
	if [[ "$V_SHORTEN" == 1 ]] ; then
		F.SHORT
	else
		${COMM}
	fi
fi

} 
#======================================================}


#============================================={
case $1 in
	"--my-tree")
		PID="$2"
		TREE=2
		# Part of lib/lib.short
		F.TREE
		echo "$PROC_PSTREE_OUT"
	;;
	"--ps-tree") pstree -ptsa "$2" ;;
	"--trees")
		pstree -pa
	;;
	"--help"|"-h")
		NETMONIT.HELP
	;;
#====================
	--lsof)    COMM="COMM.LSOF"    ; shift ; LEVEL11 "$@" ;;
	--netstat) COMM="COMM.NETSTAT" ; shift ; LEVEL11 "$@" ;;
	--ss)      COMM="COMM.SS"      ; shift ; LEVEL11 "$@" ;;
#====================
	--display-log) echo "-display-log"  ; 
					cat /var/log/netmonit.log
	#---------------------------{
	#	shift ; 
	#	case "$1" in
	#		--last-hour) l1=1 ;;
	#		--last-day)  l2=2 ;;
	#		--all)       l3=3 ;;
	#		*)  echo "Error: With argument --display-log . Wrong next argument $1 "
	#			echo "Available arguments: "
	#			echo "	--last-hour" 
	#			echo "	--last-day" 
	#			echo "	--all" 
	#			exit ;;
	#	esac
	#---------------------------}
		exit 0
	;;
	#--filter-log) echo "--filter-log"  ; shift ; 
	#---------------------------{
	#	case "$1" in
	#		--most-of-all) l1=1 ;;
	#		--least-of-all)  l2=2 ;;
	#		*)  echo "Error: With argument --filter-log . Wrong next argument $1 " 
	#			echo "Available arguments: "
	#			echo "	--most-of-all" 
	#			echo "	--least-of-all" 
	#			exit ;;
	#	esac
	#---------------------------}
	#	exit 0
	#;;
	--remove-log)       rm -v  /var/log/netmonit.log     ; exit 0 ;;
	--watch-log)      tail -f  /var/log/netmonit.log     ; exit 0 ;;
	*)
		echo "Unknown argument: $1"
		echo "	Try use: $0 --help"
	;; 
esac
#=============================================}
	
