#!/bin/bash


#=============================================================================={
##    Destiny:    Graphical User Interface for " netmonit --catch-all-with-lsof "
##                  For more comfortable use of netmonit logs.
     VERSION="2" 
##    Date:       2024.11.27 (Year.Month.Day) 
##    License:    GNU GPL v.3   http://www.gnu.org/licenses/gpl-3.0.en.html 
##    Source:   "https://github.com/tele1/LinuxScripts"
##    Script usage:   bash gfnetmonit
#==============================================================================}


#=============================================================================={
# Check Dependecies - List created automatically by find-bash-dep version=11 
# source=https://github.com/tele1/LinuxScripts
 
[[ -z $(type -P awk) ]] && DEP="$DEP"$'\n'"awk"
[[ -z $(type -P basename) ]] && DEP="$DEP"$'\n'"basename"
[[ -z $(type -P bash) ]] && DEP="$DEP"$'\n'"bash"
[[ -z $(type -P cat) ]] && DEP="$DEP"$'\n'"cat"
[[ -z $(type -P echo) ]] && DEP="$DEP"$'\n'"echo"
[[ -z $(type -P grep) ]] && DEP="$DEP"$'\n'"grep"
[[ -z $(type -P ls) ]] && DEP="$DEP"$'\n'"ls"
[[ -z $(type -P printf) ]] && DEP="$DEP"$'\n'"printf"
[[ -z $(type -P pstree) ]] && DEP="$DEP"$'\n'"pstree"
[[ -z $(type -P realpath) ]] && DEP="$DEP"$'\n'"realpath"
[[ -z $(type -P sed) ]] && DEP="$DEP"$'\n'"sed"
[[ -z $(type -P tail) ]] && DEP="$DEP"$'\n'"tail"
[[ -z $(type -P wc) ]] && DEP="$DEP"$'\n'"wc"
[[ -z $(type -P yad) ]] && DEP="$DEP"$'\n'"yad"
 
# End script if exist any error
[ -z "$DEP" ] || { echo "   Error: Missing dependencies, before run script please install: $DEP"  ; exit 1  ;}
 
#     Used Packages: coreutils,gawk,psmisc,yad,
#=============================================================================={


##  Relative Path needed for read other files from other place
Relativ_Path="$(dirname "$(realpath $0)")"

##      Menu in system tray icon
Func_win1() {
    ## option --seperator is for --menu
    yad --title="Test_window" --notification --image="$System_Tray" --text "$0 : Right click to open menu" \
    --command='echo "- Idea. Building a better world." ' \
    --listen --menu="
    List!bash ${Relativ_Path}/data/bin/win2
    Logs!xdg-open /var/log/netmonit
    Close This Menu
    Close App!quit" \
    --separator="\\n" \
    
}


System_Tray="gtk-yes"
Func_win1

